// <auto-generated />
namespace tshirt.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class MyMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MyMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201406170743537_MyMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
